name: Check links

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --accept 200,204,206,301,302,303,307,308,403,429,999 --exclude-path node_modules README.md CONTRIBUTING.md
          fail: true
